#!/bin/bash

if [[ "$SHELL" = "zsh" ]]; then
  FZF_SOURCE=~/.fzf.zsh
else
  FZF_SOURCE=~/.fzf.sh
fi

# Upgrade fzf
function upgrade_fzf() {
  cd ~/.fzf && git pull && ./install --all --no-update-rc
  [ -f $FZF_SOURCE ] && source $FZF_SOURCE
}

export FZF_DEFAULT_OPTS="--height 40% --reverse"

# Load fzf
[ -f $FZF_SOURCE ] && source $FZF_SOURCE
