#!/bin/sh

# update & upgrade
#
# debian/ubuntu
if command -v apt >& /dev/null; then
  sudo apt -y update
  sudo apt -y upgrade
# el8+
elif command -v dnf >& /dev/null; then
  sudo dnf -y update
# el7
elif command -v yum >& /dev/null; then
  sudo yum -y update
fi
